# fly.toml app configuration file generated for misty99-app on 2026-10-06T11:20:02Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'misty99-app'
primary_region = 'arn'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
